name: 'Asana Github Issues Integration'
description: 'Create Asana task based on a Github Issue'
inputs:
  asana-pat:
    description: 'Asana Public Access Token.'
    required: true
  asana-project:
    description: 'Asana Project Id where the Tasks will be added.'
    required: true
  action:
    description: 'Action that will be executed. `create-task` to create a task based on the ISSUE'
    required: true
branding:
  icon: 'chevron-right'
  color: 'gray-dark'
runs:
  using: 'node16'
  main: 'index.js'
